# 应用名称
appName: "ms-tools"
appVersion: 1.0

# 统一默认日志配置
defaultLogger: &defaultLogger
  level: "all"
  flags: 42
  file: "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
  stdoutColorDisabled: false # 关闭终端的颜色打印。默认开启
  writerColorEnable: false # 日志文件是否带上颜色。默认false，表示不带颜色
  rotateExpire: "7d" # 日志保留天数
  rotateBackupLimit: 2 # 最大备份数量
  rotateBackupCompress: 2 # 日志文件压缩级别，0-9,9最高

# 日志配置
logger:
  # 全局日志：g.Log()
  path: "logs/logger" # 日志文件路径。默认为空，表示关闭，仅输出到终端
  <<: *defaultLogger
  # xhs：g.Log("xhs")
  xhs:
    path: "logs/xhs" # 日志文件路径。默认为空，表示关闭，仅输出到终端
    <<: *defaultLogger
  # dy：g.Log("dy")
  dy:
    path: "logs/dy" # 日志文件路径。默认为空，表示关闭，仅输出到终端
    <<: *defaultLogger
#缓存
cache:
  adapter: "file" # 缓存驱动方式，支持：memory|redis|file，不填默认memory
  fileDir: "./storage/cache" # 文件缓存路径，adapter=file时必填